language: python

services:
  - docker

before_install:
  - docker --version

install:
    - docker build -t gospl .

script:
  - docker run -it --entrypoint /bin/bash gospl -c "cd /live/lib/gospl; python3 -m pytest --cov=."

# after_success:
#   - coveralls --data_file=.coverage
