language: python

os: linux

dist: xenial

services:
  - docker

before_install:
  - docker --version

install:
    - docker build -t gospl .

script:
  - docker run -it --entrypoint /bin/bash gospl -c "cd /live/lib/gospl; mpirun -np 2 python3 -m pytest --with-mpi --cov=."

after_success:
  - docker run -it --entrypoint /bin/bash gospl -c "cd /live/lib/gospl; mpirun -np 2 python3 -m pytest --with-mpi --cov=.; COVERALLS_REPO_TOKEN=sl7N2VlsshmA5W8zt7uv3nYid6adiWY6D coveralls --rcfile=.coveragerc"
