language: python

services:
  - docker

before_install:
  - docker --version

install:
    - docker build -t gospl .

script:
  - docker run -it --entrypoint /bin/bash gospl -c "cd /live/lib/gospl; python3 -m pytest --cov=.; COVERALLS_REPO_TOKEN=sl7N2VlsshmA5W8zt7uv3nYid6adiWY6D coveralls --rcfile=/live/lib/gospl/.coveragerc"
