services:
  - docker

os: debian

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - docker --version

install:
    - docker build -t gospl .

script:
  - docker run -it --entrypoint /bin/bash gospl -c "pip3 install pytest-cov; cd lib/gospl; ls; python3 -m pytest --cov=."

# after_success:
#   - coveralls --data_file=.coverage
