name: gospl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - meson-python>=0.15.0
  - setuptools>=61.0
  - pkg-config
  - build
  - numpy
  - petsc4py
  - scipy
  - numpy-indexed
  - pandas
  - h5py
  - meshio
  - vtk
  - ruamel.yaml
  - gflex
  - mpi4py
  - xarray
  - rioxarray
  - pyproj
  - cython
  - compilers
  - pip:
    - git+https://github.com/Geodels/isoFlex.git
    - git+https://github.com/Geodels/gospl.git
